### ISSUE TITLE
Website doesn't mention what MREs will actually be there

### ISSUE THREAD

**Issue by AverseABFun** [hackclub/the-trail#8]
I am not _super_ picky, but I still like to know what food will be available. The website mentions MREs and has a link to the Back Packer's Pantry, but it doesn't mention what kind of MREs will be there.

**Comment by SerenityUX** [comment]
We have not picked the specific MREs, but they'll be from this site:
https://backpackerspantry.com/collections/food

I am thinking we'll let each person decide what meals they want from the site.

**Comment by AverseABFun** [comment]
That'd be great!

**Comment by Swamstick911** [comment]
Umm.. I am veg!

**Comment by AverseABFun** [comment]
There are veg options!

**Comment by Swamstick911** [comment]
Oh thank god!!
